apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: image-clf-train-tutorial
  annotations:
    scenarios.ai.sap.com/description: "SAP developers tutorial scenario"
    scenarios.ai.sap.com/name: "image-clf-tutorial-scenario"
    executables.ai.sap.com/description: "Image classification training executable"
    executables.ai.sap.com/name: "image-clf-train-tutorial-exec"
    artifacts.ai.sap.com/image-data.kind: "dataset"
    artifacts.ai.sap.com/image-model-tutorial.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "image-clf-tutorial"
    executables.ai.sap.com/id: "image-clf-train-tutorial"
    ai.sap.com/version: "1.0.0"
spec:
  imagePullSecrets:
    - name: docker-registry-secret
  entrypoint: image-clf-sk-training
  templates:
    - name: image-clf-sk-training
      metadata:
        labels:
          ai.sap.com/resourcePlan: starter
      inputs:
        artifacts:
          - name: image-data
            path: /app/data/
      outputs:
        artifacts:
          - name: image-model-tutorial
            path: /app/model
            globalName: image-model-tutorial
            archive:
              none: {}
      container:
        image: "docker.io/yoshidj/image-clf-train:0.0.1"
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - >
            set -e && echo "---Start Training---" && python /app/src/train.py && ls -lR /app/model && echo "---End Training---"
